# Generated by Django 4.1.5 on 2023-03-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoshiq',
            name='fayl',
            field=models.FileField(upload_to=''),
        ),
    ]
