# Generated by Django 4.1.5 on 2023-03-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_qoshiq_fayl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoshiq',
            name='fayl',
            field=models.URLField(),
        ),
    ]
